import "./globals.css"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer/Footer"

export const metadata = {
  title: "RiskThinking - Work Sample",
  description: "Generated by create next app",
}
const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} font-inter tracking-tight`}>
      <body className="min-h-screen">
        <>
          <Navbar />
          {children}
          <Footer />
        </>
      </body>
    </html>
  )
}
